//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class areas
    {
        public int area { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string titular { get; set; }
        public byte[] logoarea { get; set; }
        public short FUP { get; set; }
        public string idsupzona { get; set; }
        public string idjefsector { get; set; }
        public string rfc { get; set; }
        public byte[] firma { get; set; }
        public Nullable<bool> activa { get; set; }
    }
}
