//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bit_cap_mov_sibl
    {
        public int id { get; set; }
        public int id_captura { get; set; }
        public int estatus_op { get; set; }
        public string usuario { get; set; }
        public string operacion { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual captura_mov_sibl captura_mov_sibl { get; set; }
    }
}
