//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class captura_mov_sibl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public captura_mov_sibl()
        {
            this.bit_cap_mov_sibl = new HashSet<bit_cap_mov_sibl>();
            this.documentos_cap_sibl = new HashSet<documentos_cap_sibl>();
            this.plazas_cap_sibl = new HashSet<plazas_cap_sibl>();
        }
    
        public int id_captura { get; set; }
        public short area { get; set; }
        public int id_tipo_mov { get; set; }
        public int id_empleado { get; set; }
        public string rfc { get; set; }
        public string ct { get; set; }
        public Nullable<System.DateTime> fecha_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<System.DateTime> fecha_captura { get; set; }
        public Nullable<System.DateTime> fecha_alerta { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_recibido { get; set; }
        public Nullable<System.DateTime> fecha_cancelacion { get; set; }
        public string observacion { get; set; }
        public string usuario_cap { get; set; }
        public Nullable<short> estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bit_cap_mov_sibl> bit_cap_mov_sibl { get; set; }
        public virtual captura_mov_sibl captura_mov_sibl1 { get; set; }
        public virtual captura_mov_sibl captura_mov_sibl2 { get; set; }
        public virtual empleado_u empleado_u { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_cap_sibl> documentos_cap_sibl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plazas_cap_sibl> plazas_cap_sibl { get; set; }
        public virtual tipo_mov_sibl tipo_mov_sibl { get; set; }
    }
}
