//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciones
    {
        public int Id { get; set; }
        public int Num_App { get; set; }
        public string Sistema { get; set; }
        public Nullable<int> Ciclo_Escolar { get; set; }
        public Nullable<System.DateTime> Fecha_Apertura { get; set; }
        public Nullable<System.DateTime> Fecha_Cierre { get; set; }
        public string Titulo { get; set; }
        public string Leyenda_PC { get; set; }
    }
}
