//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion_sibl
    {
        public int id_configuracion { get; set; }
        public short periodo_abierto { get; set; }
        public string leyenda { get; set; }
    }
}
