//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_basico
    {
        public short ent_fed { get; set; }
        public string ct_clasif { get; set; }
        public string ct_id { get; set; }
        public short ct_secuencial { get; set; }
        public string ct_digito_ver { get; set; }
        public string clave_ct { get; set; }
        public string ct_nombre { get; set; }
        public string ct_dom { get; set; }
        public string ct_calle { get; set; }
        public string ct_calle1 { get; set; }
        public short municipio { get; set; }
        public short localidad { get; set; }
        public string ct_cp { get; set; }
        public string ct_tel { get; set; }
        public string ct_fax { get; set; }
        public string ct_nomdir { get; set; }
        public Nullable<short> ct_dep_admva { get; set; }
        public string ct_dep_norm { get; set; }
        public short zona_escolar { get; set; }
        public string ct_depto_se_re { get; set; }
        public Nullable<short> ct_sector { get; set; }
        public string ct_alm_dis { get; set; }
        public string ct_area_geo { get; set; }
        public Nullable<short> ct_sosten { get; set; }
        public string ct_serv { get; set; }
        public Nullable<short> turno { get; set; }
        public string ct_cve_inm { get; set; }
        public string ct_tip_cor { get; set; }
        public string ct_num_cor { get; set; }
        public string ct_fec_cor { get; set; }
        public string ct_cve_eco { get; set; }
        public string ct_fec_fun { get; set; }
        public Nullable<short> estatus_ct { get; set; }
        public string ct_fec_alt { get; set; }
        public string ct_fec_act { get; set; }
        public string unidad_resp { get; set; }
        public string programa { get; set; }
        public string subprograma { get; set; }
        public string op { get; set; }
        public string rfc { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<short> unidad_dist_cheque { get; set; }
        public string operador { get; set; }
    }
}
