//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_cap_sibl
    {
        public int id_doc_sibl { get; set; }
        public int id_captura { get; set; }
        public int id_doc_tipdoc { get; set; }
        public string path { get; set; }
        public System.DateTime fecha { get; set; }
        public int estatus { get; set; }
    
        public virtual doc_tipomov_sibl doc_tipomov_sibl { get; set; }
        public virtual captura_mov_sibl captura_mov_sibl { get; set; }
    }
}
