//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_plaza_pmp
    {
        public string rfc { get; set; }
        public short cod_pago { get; set; }
        public short unidad { get; set; }
        public short subunidad { get; set; }
        public string cat_puesto { get; set; }
        public double horas { get; set; }
        public int cons_plaza { get; set; }
        public short estatus_plaza { get; set; }
        public int qna_ini { get; set; }
        public int qna_fin { get; set; }
        public short mot_mov { get; set; }
        public short nivel_sueldo { get; set; }
    }
}
