//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado_u
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado_u()
        {
            this.captura_mov_sibl = new HashSet<captura_mov_sibl>();
        }
    
        public int id { get; set; }
        public string rfc { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string nom { get; set; }
        public string nom_emp { get; set; }
        public string sexo { get; set; }
        public short edo_civil { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public short edo_nac { get; set; }
        public string lug_nac { get; set; }
        public string nombre_padre { get; set; }
        public string nombre_madre { get; set; }
        public Nullable<int> acta_no { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> foja { get; set; }
        public Nullable<int> libro { get; set; }
        public string cartilla_smn { get; set; }
        public Nullable<short> clase { get; set; }
        public string estatus_cartilla { get; set; }
        public string nombre_esposo_a { get; set; }
        public string lugar_filiacion { get; set; }
        public Nullable<System.DateTime> fecha_filiacion { get; set; }
        public Nullable<System.DateTime> fecha_examen { get; set; }
        public Nullable<int> qna_ini { get; set; }
        public string act_inact { get; set; }
        public short ban_pago { get; set; }
        public short mot_baja { get; set; }
        public int qna_baja { get; set; }
        public Nullable<int> qna_ing_gob { get; set; }
        public Nullable<int> qna_ing_sep { get; set; }
        public Nullable<int> qna_ing_hon { get; set; }
        public Nullable<int> qna_ing_pro { get; set; }
        public string niv_academico { get; set; }
        public string escuela_egreso { get; set; }
        public Nullable<short> anio_egreso { get; set; }
        public string titulado { get; set; }
        public short tipo_tit { get; set; }
        public short tipo_lic { get; set; }
        public int num_tit { get; set; }
        public int num_lic { get; set; }
        public string emp_cta_sar { get; set; }
        public double acumulado_horas_42 { get; set; }
        public double acumulado_horas_48 { get; set; }
        public string emp_dom { get; set; }
        public string emp_dom_col { get; set; }
        public string emp_dom_pob { get; set; }
        public string emp_dom_tel { get; set; }
        public string emp_dom_cel { get; set; }
        public string emp_dom_cp { get; set; }
        public string emp_dom_calle { get; set; }
        public string emp_dom_num { get; set; }
        public string emp_dom_numint { get; set; }
        public Nullable<short> emp_dom_mun { get; set; }
        public Nullable<short> emp_dom_loc { get; set; }
        public string emp_cta_bancaria { get; set; }
        public short bco_admdor { get; set; }
        public short bco_plaza { get; set; }
        public Nullable<System.DateTime> fecha_def { get; set; }
        public System.DateTime creacion { get; set; }
        public string curp { get; set; }
        public string email { get; set; }
        public string usuario { get; set; }
        public string senial { get; set; }
        public string edocivil { get; set; }
        public string nivacademico { get; set; }
        public string efreside { get; set; }
        public Nullable<short> edad { get; set; }
        public bool sistema { get; set; }
        public string id_pais { get; set; }
        public Nullable<short> mun_nac { get; set; }
        public Nullable<short> emp_dom_ent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<captura_mov_sibl> captura_mov_sibl { get; set; }
    }
}
