//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hpc_pmp
    {
        public string u_version { get; set; }
        public short cod_pago { get; set; }
        public short unidad { get; set; }
        public short subunidad { get; set; }
        public string cat_puesto { get; set; }
        public double horas { get; set; }
        public int cons_plaza { get; set; }
        public short ent_fed { get; set; }
        public string ct_clasif { get; set; }
        public string ct_id { get; set; }
        public short ct_secuencial { get; set; }
        public string ct_digito_ver { get; set; }
        public int qna_fin { get; set; }
        public int qna_ini { get; set; }
        public int num_doc { get; set; }
        public Nullable<System.DateTime> fec_doc { get; set; }
    }
}
