//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class motivos_mov
    {
        public string u_version { get; set; }
        public short mot_mov { get; set; }
        public string estatus_lec_hpe { get; set; }
        public string estatus_esc_hpe { get; set; }
        public string estatus_cie_hpe { get; set; }
        public string estatus_lec_ep { get; set; }
        public string estatus_esc_ep { get; set; }
        public string estatus_cie_ep { get; set; }
        public string descripcion { get; set; }
    }
}
