//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvc_permisos
    {
        public int clave_app { get; set; }
        public int clave_mod { get; set; }
        public string usuario { get; set; }
        public string permisos { get; set; }
        public string valor { get; set; }
    }
}
