//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMOV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_mov_sibl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_mov_sibl()
        {
            this.captura_mov_sibl = new HashSet<captura_mov_sibl>();
            this.doc_tipomov_sibl = new HashSet<doc_tipomov_sibl>();
        }
    
        public int id_tipo { get; set; }
        public short cve_mov { get; set; }
        public short mot_movcap { get; set; }
        public Nullable<short> dias_soliditud { get; set; }
        public string personal_con_derecho { get; set; }
        public string requisitos { get; set; }
        public string duracion { get; set; }
        public string prorroga { get; set; }
        public string base_legal { get; set; }
        public string doc_solicitud { get; set; }
        public short all_plazas { get; set; }
        public short estatus { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<captura_mov_sibl> captura_mov_sibl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_tipomov_sibl> doc_tipomov_sibl { get; set; }
    }
}
